name: Auto Check-in

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 0:00 执行（北京时间 8:00）
  workflow_dispatch:  # 允许手动运行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Check-in Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkin.py
