name: 自动签到

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 00:00 UTC 运行
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 和依赖
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
          pip install selenium

      - name: 运行签到脚本
        run: python autoqiandao.py
